import { WikiCssGenerator } from "../generator/wiki-css-generator"
import { WikiBuilder } from "../model/embedded/WikiBuilder"
import { AlignContent } from "../model/kernel/models/enum/align-content.enum"
import { Color } from "../model/kernel/models/enum/color.enum"
import { TextDecoration } from "../model/kernel/models/enum/text-decoration.enum"
import { UnitySize } from "../model/kernel/models/enum/unity-font-size.enum"


const wikiBuilder = WikiBuilder.createWiki()

wikiBuilder
    .editContentBoxStyle() 
        .setBackgroundColor("#262121")
        .setMargin(0)
        .setPaddingSides(5,10,10,10,UnitySize.PERCENT)
    .endBlockEdit()
    .editContentStyle()
        .editTextStyle()
            .editTextStyle()
                .setFontColor(Color.WHITE)
                .setPolice("rubik")
                .setFontSize(13)
            .endTextEdit()
            .editLinkTextStyle()
                .setFontColor("#F8CA01")
            .endTextEdit()
        .endTextEdit()
        .editButtonStyle()
            .editButtonTextStyle()
                .putInBold()
                .centerText()
                .setFontColor(Color.WHITE)
                .underlined(TextDecoration.NONE)
            .endTextEdit()
            .editContentBoxStyle()
                .setBackgroundColor("#F8CA01")
                .setBorderRadius(20)
                .setPadding(10)
                .setMarginSides(10,0,10,0)
            .endBlockEdit()
        .endButtonEdit()
        .editImageStyle()
            .editContentBoxStyle()
                .centerContent()
                .setWidth(350)
            .endBlockEdit()
            .editAbstractTextStyle()
                .setFontColor(Color.WHITE)
                .italicize()
                .setFontSize(11)
            .endTextEdit()
        .endImageEdit()

wikiBuilder.editSubjectStyle()
    .editTitleStyle()
        .editContentStyle()
            .setFontColor(Color.WHITE)
        .endTextEdit()
    .endTitleEdit()
    
wikiBuilder.editSubjectStyle().editChapterStyle()
    .editTitleStyle()
        .editContentBoxStyle()
            .setBorderBot(1,"#565252")
            .setPaddingSides(0,0,10,0)
        .endBlockEdit()
    .endTitleEdit()

wikiBuilder.editSubjectStyle().editChapterStyle().editSubChapterStyle()
    .editTitleStyle()
        .editContentBoxStyle()
            .setBorderBot(0)
        .endBlockEdit()
        .editContentStyle()
            .setFontSize(15)
        .endTextEdit()
    .endTitleEdit()

wikiBuilder.editNavBarStyle()
    .editContentBoxStyle()
        .setPadding(15)
        .setBackgroundColor("#353030")
        .setBorder(1,"#5A5485")
    .endBlockEdit()
    .editContentStyle()
        .editTextStyle()
            .editTextStyle()
                .putInBold()
                .setFontColor("#F8CA01")
                .setFontSize(18)
            .endTextEdit()
            .editLinkTextStyle()
                .underlined(TextDecoration.NONE)
            .endTextEdit()
        .endTextEdit()
    

wikiBuilder.editSubjectStyle().editTableOfContentStyle()
    .editContentBoxStyle() 
        .setBorder(1,"#565252")
        .setPaddingSides(0,0,0,0)
    .endBlockEdit()
    .editTitleStyle()
        .editContentBoxStyle() 
            .setBorderBot(1,"#565252")
        .endBlockEdit()
        .editContentBoxStyle()
            .setPaddingSides(0,0,10,10)
        .endBlockEdit()
    .endTitleEdit()
    .editContentStyle()
        .editTextStyle()
            .editLinkTextStyle()
                .setFontColor(Color.WHITE)
            .endTextEdit()
        .endTextEdit();

wikiBuilder.editSubjectStyle().editReferenceStyle()
    .editTitleStyle()
        .editContentStyle()
            .centerText()
        .endTextEdit()
    .endTitleEdit()
    .editContentBoxStyle() 
        .setBackgroundColor("#353030")
        .setBorder(1,"#5A5485")
        .setPaddingSides(0,15,5,15)
    .endBlockEdit()

wikiBuilder.editSubjectStyle().editRelatedSubjectStyle()
    .editTitleStyle()
        .editContentStyle()
            .centerText()
        .endTextEdit()
    .endTitleEdit()
    .editContentBoxStyle() 
        .setBackgroundColor("#353030")
        .setBorder(1,"#5A5485")
        .setPaddingSides(0,15,5,15)
    .endBlockEdit()

wikiBuilder.editContentStyle().editTableStyle()
    .editCellBox()
        .setBackgroundColor("#161111")
        .setBorder(2,"#F8CA01")
    .endBlockEdit()
    .editHeaderColumnCellBox()
        .setBackgroundColor("#060101")
    .endBlockEdit()
    .editHeaderRowCellBox()
        .setBackgroundColor("#363131")
    .endBlockEdit()
    .editTableBox()
        .centerContent()
        .setWidth(80,UnitySize.PERCENT)


export const SlayTheSpireModel = wikiBuilder.createModel();
const cssGenerator = new WikiCssGenerator();

