import { ChapterContent, ClassiqueChapterContent, GalleryChapterContent, ImageContent, InfoBoxContent, ReferencesContent, RelatedSubjectContent, SubjectContent, SummaryContent, TableContent, TextContent, TOCContent } from "../kernel/models/content";

const diceArray:TableContent = new TableContent(
    [
        [new TextContent("Dice"),new TextContent("min value"),new TextContent("max value")],
        [new TextContent("4"),new TextContent("1"),new TextContent("4")],
        [new TextContent("6"),new TextContent("1"),new TextContent("6")],
        [new TextContent("8"),new TextContent("1"),new TextContent("8")],
        [new TextContent("10"),new TextContent("1"),new TextContent("10")],
        [new TextContent("12"),new TextContent("1"),new TextContent("12")],
        [new TextContent("20"),new TextContent("1"),new TextContent("20")],
        [new TextContent("100"),new TextContent("1"),new TextContent("100")]],
        true,true
)
const chapter1p1:ChapterContent = new ClassiqueChapterContent(
    "Game mechanics",
    [
        new ImageContent("/images/DD_Dice.jpg","D&D uses polyhedral dice to resolve in-game events. These are abbreviated by a 'd' followed by the number of sides. Shown from left to right are a d20, a d12, a d100, a d10, a d8, a d6, and a d4. A d100 and a d10 can be rolled together to produce a number between 1 and 100."),

        new TextContent(`Before the game begins, each player <a href="https://en.wikipedia.org//wiki/Character_creation" title="Character creation">creates</a> their player character and records the details (described below) on a character sheet. First, a player determines their character's <a href="https://en.wikipedia.org//wiki/Game_mechanics_(Dungeons_%26_Dragons)#Ability_scores" class="mw-redirect" title="Game mechanics (Dungeons &amp; Dragons)">ability scores</a>, which consist of Strength, Constitution, Dexterity, Intelligence, Wisdom, and Charisma. Each edition of the game has offered differing methods of determining these scores.<sup id="cite_ref-31" class="reference"><a href="#cite_note-31">[31]</a></sup> The player then chooses a race (species) such as human or elf, a <a href="https://en.wikipedia.org//wiki/Character_class_(Dungeons_%26_Dragons)" title="Character class (Dungeons &amp; Dragons)">character class</a> (occupation) such as fighter or wizard, an <a href="https://en.wikipedia.org//wiki/Alignment_(Dungeons_%26_Dragons)" title="Alignment (Dungeons &amp; Dragons)">alignment</a> (a moral and ethical outlook), and other features to round out the character's abilities and backstory, which have varied in nature through differing editions.        `),
        new TextContent(`During the game, players describe their PCs' intended actions, such as punching an opponent or picking a lock, and converse with the DM, who then describes the result or response.<sup id="cite_ref-32" class="reference"><a href="#cite_note-32">[32]</a></sup> Trivial actions, such as picking up a letter or opening an unlocked door, are usually automatically successful. The outcomes of more complex or risky actions are determined by rolling dice.<sup id="cite_ref-Culture_chapter_33-0" class="reference"><a href="#cite_note-Culture_chapter-33">[33]</a></sup> Different polyhedral dice are used for different actions, such as a twenty-sided die to see whether a hit was made in combat, but an eight-sided die to determine how much damage was dealt.<sup id="cite_ref-34" class="reference"><a href="#cite_note-34">[34]</a></sup> Factors contributing to the outcome include the character's ability scores, skills and the difficulty of the task.<sup id="cite_ref-35" class="reference"><a href="#cite_note-35">[35]</a></sup> In circumstances where a character does not have control of an event, such as when a trap or magical effect is triggered or a spell is cast, a <a href="https://en.wikipedia.org//wiki/Saving_throw" title="Saving throw">saving throw</a> can be used to determine whether the resulting damage is reduced or avoided.<sup id="cite_ref-PHB_p.136_36-0" class="reference"><a href="#cite_note-PHB_p.136-36">[36]</a></sup><sup id="cite_ref-37" class="reference"><a href="#cite_note-37">[37]</a></sup> In this case the odds of success are influenced by the character's class, levels and ability scores.<sup id="cite_ref-PHB_p.136_36-1" class="reference"><a href="#cite_note-PHB_p.136-36">[36]</a></sup><sup id="cite_ref-38" class="reference"><a href="#cite_note-38">[38]</a></sup>
        `),
        new TextContent(`As the game is played, each PC changes over time and generally increases in capability. Characters gain (or sometimes lose) experience, skills<sup id="cite_ref-39" class="reference"><a href="#cite_note-39">[39]</a></sup> and wealth, and may even alter their alignment<sup id="cite_ref-40" class="reference"><a href="#cite_note-40">[40]</a></sup> or gain <a href="https://en.wikipedia.org//wiki/Character_class_(Dungeons_%26_Dragons)#Multi-classing" title="Character class (Dungeons &amp; Dragons)">additional character classes</a>.<sup id="cite_ref-41" class="reference"><a href="#cite_note-41">[41]</a></sup> The key way characters progress is by earning <a href="https://en.wikipedia.org//wiki/Experience_point" title="Experience point">experience points</a> (XP), which happens when they defeat an enemy or accomplish a difficult task.<sup id="cite_ref-42" class="reference"><a href="#cite_note-42">[42]</a></sup> Acquiring enough XP allows a PC to advance a <a href="https://en.wikipedia.org//wiki/Experience_level" class="mw-redirect" title="Experience level">level</a>, which grants the character improved class features, abilities and skills.<sup id="cite_ref-43" class="reference"><a href="#cite_note-43">[43]</a></sup> XP can be lost in some circumstances, such as encounters with creatures that drain life energy, or by use of certain magical powers that come with an XP cost.<sup id="cite_ref-44" class="reference"><a href="#cite_note-44">[44]</a></sup>
        `),
        new TextContent(`<a href="https://en.wikipedia.org//wiki/Hit_point" class="mw-redirect" title="Hit point">Hit points</a> (HP) are a measure of a character's vitality and health and are determined by the class, level and constitution of each character. They can be temporarily lost when a character sustains wounds in combat or otherwise comes to harm, and loss of HP is the most common way for a character to die in the game.<sup id="cite_ref-45" class="reference"><a href="#cite_note-45">[45]</a></sup> Death can also result from the loss of key ability scores<sup id="cite_ref-46" class="reference"><a href="#cite_note-46">[46]</a></sup> or character levels.<sup id="cite_ref-47" class="reference"><a href="#cite_note-47">[47]</a></sup> When a PC dies, it is often possible for the dead character to be resurrected through magic, although some penalties may be imposed as a result. If resurrection is not possible or not desired, the player may instead create a new PC to resume playing the game.<sup id="cite_ref-48" class="reference"><a href="#cite_note-48">[48]</a></sup>
        `),
        diceArray
    ]
)
const chapter1p2:ChapterContent = new ClassiqueChapterContent(
    "Adventures and campaigns",
    [
        new ImageContent("/images/DD_notebook.jpg","A Dungeon Master's notebook with a custom design adventure"),

        new TextContent(`A typical <i>Dungeons &amp; Dragons</i> game consists of an "adventure", which is roughly equivalent to a single story.<sup id="cite_ref-49" class="reference"><a href="#cite_note-49">[49]</a></sup> The DM can either design an original adventure, or follow one of the many pre-made adventures (also known as "modules") that have been published throughout the history of <i>Dungeons &amp; Dragons</i>. Published adventures typically include a background story, illustrations, maps and goals for PCs to achieve. Some include location descriptions and handouts. Although a small adventure entitled "<a href="https://en.wikipedia.org//wiki/Temple_of_the_Frog" title="Temple of the Frog">Temple of the Frog</a>" was included in the <i><a href="https://en.wikipedia.org//wiki/Blackmoor_(supplement)" title="Blackmoor (supplement)">Blackmoor</a></i> rules supplement in 1975, the first stand-alone <i>D&amp;D</i> module published by TSR was 1978's <i><a href="https://en.wikipedia.org//wiki/Steading_of_the_Hill_Giant_Chief" class="mw-redirect" title="Steading of the Hill Giant Chief">Steading of the Hill Giant Chief</a></i>, written by Gygax.
        `),
        new TextContent(`A linked series of adventures is commonly referred to as a "<a href="https://en.wikipedia.org//wiki/Campaign_(role-playing_games)" title="Campaign (role-playing games)">campaign</a>".<sup id="cite_ref-50" class="reference"><a href="#cite_note-50">[50]</a></sup> The locations where these adventures occur, such as a city, country, planet or an entire <a href="https://en.wikipedia.org//wiki/Fictional_universe" title="Fictional universe">fictional universe</a>, are referred to as "<a href="https://en.wikipedia.org//wiki/Campaign_setting" title="Campaign setting">campaign settings</a>" or "world".<sup id="cite_ref-51" class="reference"><a href="#cite_note-51">[51]</a></sup> <i>D&amp;D</i> settings are based in various fantasy genres and feature different levels and types of magic and technology.<sup id="cite_ref-52" class="reference"><a href="#cite_note-52">[52]</a></sup> Popular commercially published <a href="https://en.wikipedia.org//wiki/Dungeons_%26_Dragons_campaign_settings" title="Dungeons &amp; Dragons campaign settings">campaign settings for <i>Dungeons &amp; Dragons</i></a> include <a href="https://en.wikipedia.org//wiki/Greyhawk" title="Greyhawk">Greyhawk</a>, <a href="https://en.wikipedia.org//wiki/Dragonlance" title="Dragonlance">Dragonlance</a>, <a href="https://en.wikipedia.org//wiki/Forgotten_Realms" title="Forgotten Realms">Forgotten Realms</a>, <a href="https://en.wikipedia.org//wiki/Mystara" title="Mystara">Mystara</a>, <a href="https://en.wikipedia.org//wiki/Spelljammer" title="Spelljammer">Spelljammer</a>, <a href="https://en.wikipedia.org//wiki/Ravenloft" title="Ravenloft">Ravenloft</a>, <a href="https://en.wikipedia.org//wiki/Dark_Sun" title="Dark Sun">Dark Sun</a>, <a href="https://en.wikipedia.org//wiki/Planescape" title="Planescape">Planescape</a>, <a href="https://en.wikipedia.org//wiki/Birthright_(campaign_setting)" title="Birthright (campaign setting)">Birthright</a>, and <a href="https://en.wikipedia.org//wiki/Eberron" title="Eberron">Eberron</a>.
        `),
        new TextContent(`In addition to first-party campaigns and modules, two campaigns based on popular culture have been created. The first, based on <i><a href="https://en.wikipedia.org//wiki/Stranger_Things" title="Stranger Things">Stranger Things</a></i>, was released in May 2019.<sup id="cite_ref-53" class="reference"><a href="#cite_note-53">[53]</a></sup><sup id="cite_ref-54" class="reference"><a href="#cite_note-54">[54]</a></sup> A campaign based on the <a href="https://en.wikipedia.org//wiki/Rick_and_Morty#Comics" title="Rick and Morty"><i>Rick and Morty vs. Dungeons and Dragons</i></a> comic book series was later released in November 2019.<sup id="cite_ref-55" class="reference"><a href="#cite_note-55">[55]</a></sup><sup id="cite_ref-56" class="reference"><a href="#cite_note-56">[56]</a></sup>
        `),
        new TextContent(`Alternatively, DMs may develop their own fictional worlds to use as campaign settings.
        `)
    ]
)
const chapter1p3:ChapterContent = new ClassiqueChapterContent(
    "Miniature figures",
    [
        new ImageContent("/images/DD_Miniatures_2.jpg","Dungeons & Dragons miniature figures. The grid mat underneath uses one-inch squares."),
        new TextContent(`The <a href="https://en.wikipedia.org//wiki/Wargaming" class="mw-redirect" title="Wargaming">wargames</a> from which <i>Dungeons &amp; Dragons</i> evolved used miniature figures to represent combatants. <i>D&amp;D</i> initially continued the use of miniatures in a fashion similar to its direct precursors. The original <i>D&amp;D</i> set of 1974 required the use of the <i><a href="https://en.wikipedia.org//wiki/Chainmail_(game)" title="Chainmail (game)">Chainmail</a></i> miniatures game for combat resolution.<sup id="cite_ref-57" class="reference"><a href="#cite_note-57">[57]</a></sup> By the publication of the 1977 game editions, combat was mostly resolved verbally. Thus miniatures were no longer required for game play, although some players continued to use them as a visual reference.<sup id="cite_ref-58" class="reference"><a href="#cite_note-58">[58]</a></sup>
        `),
        new TextContent(`In the 1970s, numerous companies began to sell miniature figures specifically for <i>Dungeons &amp; Dragons</i> and similar games. Licensed miniature manufacturers who produced official figures include <a href="https://en.wikipedia.org//wiki/Grenadier_Miniatures" class="mw-redirect" title="Grenadier Miniatures">Grenadier Miniatures</a> (1980–1983),<sup id="cite_ref-59" class="reference"><a href="#cite_note-59">[59]</a></sup> <a href="https://en.wikipedia.org//wiki/Citadel_Miniatures" title="Citadel Miniatures">Citadel Miniatures</a> (1984–1986),<sup id="cite_ref-60" class="reference"><a href="#cite_note-60">[60]</a></sup> <a href="https://en.wikipedia.org//wiki/Ral_Partha" class="mw-redirect" title="Ral Partha">Ral Partha</a>,<sup id="cite_ref-61" class="reference"><a href="#cite_note-61">[61]</a></sup> and TSR itself.<sup id="cite_ref-62" class="reference"><a href="#cite_note-62">[62]</a></sup> Most of these miniatures used the 25&nbsp;mm scale.
        `),
        new TextContent(`Periodically, <i>Dungeons &amp; Dragons</i> has returned to its wargaming roots with supplementary rules systems for miniatures-based wargaming. Supplements such as <i><a href="https://en.wikipedia.org//wiki/Battlesystem" title="Battlesystem">Battlesystem</a></i> (1985 and 1989) and a new edition of <i>Chainmail</i> (2001)<sup id="cite_ref-63" class="reference"><a href="#cite_note-63">[63]</a></sup> provided rule systems to handle battles between armies by using miniatures.
        `)
    ]
)
const chapter1:ChapterContent = new ClassiqueChapterContent(
    "Play overview",
    [
        new TextContent(`<i>Dungeons &amp; Dragons</i> is a structured, yet fundamentally open-ended role-playing game. It is normally played indoors with the participants seated around a tabletop. Typically, one player takes on the role of <a href="https://en.wikipedia.org//wiki/Dungeon_Master" title="Dungeon Master">Dungeon Master</a> (DM) while the others each control a single character, representing an individual in a fictional setting.<sup id="cite_ref-21" class="reference"><a href="#cite_note-21">[21]</a></sup> When working together as a group, the <a href="https://en.wikipedia.org//wiki/Player_characters" class="mw-redirect" title="Player characters">player characters</a> (PCs) are often described as a "<a href="https://en.wikipedia.org//wiki/Party_(role-playing_games)" title="Party (role-playing games)">party</a>" of adventurers, with each member often having their own area of specialty which contributes to the success of the whole.<sup id="cite_ref-:7_22-0" class="reference"><a href="#cite_note-:7-22">[22]</a></sup><sup id="cite_ref-23" class="reference"><a href="#cite_note-23">[23]</a></sup> During the course of play, each player directs the actions of their character and their interactions with other characters in the game.<sup id="cite_ref-:3_7-2" class="reference"><a href="#cite_note-:3-7">[7]</a></sup> This activity is performed through the verbal impersonation of the characters by the players, while employing a variety of social and other useful cognitive skills, such as logic, basic mathematics and imagination.<sup id="cite_ref-24" class="reference"><a href="#cite_note-24">[24]</a></sup> A game often continues over a series of meetings to complete a single <a href="https://en.wikipedia.org//wiki/Adventure_(Dungeons_%26_Dragons)" title="Adventure (Dungeons &amp; Dragons)">adventure</a>, and longer into a series of related gaming adventures, called a "<a href="https://en.wikipedia.org//wiki/Campaign_(role-playing_games)" title="Campaign (role-playing games)">campaign</a>".<sup id="cite_ref-:3_7-3" class="reference"><a href="#cite_note-:3-7">[7]</a></sup><sup id="cite_ref-25" class="reference"><a href="#cite_note-25">[25]</a></sup><sup id="cite_ref-:8_26-0" class="reference"><a href="#cite_note-:8-26">[26]</a></sup>`),
        new TextContent(`The results of the party's choices and the overall storyline for the game are determined by the DM according to the rules of the game and the DM's interpretation of those rules.<sup id="cite_ref-:8_26-1" class="reference"><a href="#cite_note-:8-26">[26]</a></sup><sup id="cite_ref-:9_27-0" class="reference"><a href="#cite_note-:9-27">[27]</a></sup> The DM selects and describes the various <a href="https://en.wikipedia.org//wiki/Non-player_character" title="Non-player character">non-player characters</a> (NPCs) that the party encounters, the settings in which these interactions occur, and the outcomes of those encounters based on the players' choices and actions.<sup id="cite_ref-:3_7-4" class="reference"><a href="#cite_note-:3-7">[7]</a></sup><sup id="cite_ref-:7_22-1" class="reference"><a href="#cite_note-:7-22">[22]</a></sup> Encounters often take the form of battles with "<a href="https://en.wikipedia.org//wiki/Monsters_in_Dungeons_%26_Dragons" title="Monsters in Dungeons &amp; Dragons">monsters</a>"&nbsp;– a generic term used in <i>D&amp;D</i> to describe potentially hostile beings such as animals, aberrant beings, or mythical creatures.<sup id="cite_ref-:8_26-2" class="reference"><a href="#cite_note-:8-26">[26]</a></sup> The game's extensive rules&nbsp;– which cover diverse subjects such as social interactions,<sup id="cite_ref-:9_27-1" class="reference"><a href="#cite_note-:9-27">[27]</a></sup> <a href="https://en.wikipedia.org//wiki/Magic_of_Dungeons_%26_Dragons" class="mw-redirect" title="Magic of Dungeons &amp; Dragons">magic use</a>,<sup id="cite_ref-28" class="reference"><a href="#cite_note-28">[28]</a></sup> combat,<sup id="cite_ref-:9_27-2" class="reference"><a href="#cite_note-:9-27">[27]</a></sup> and the effect of the environment on PCs<sup id="cite_ref-29" class="reference"><a href="#cite_note-29">[29]</a></sup>&nbsp;– help the DM to make these decisions. The DM may choose to deviate from the published rules<sup id="cite_ref-:9_27-3" class="reference"><a href="#cite_note-:9-27">[27]</a></sup> or make up new ones if they feel it is necessary.<sup id="cite_ref-30" class="reference"><a href="#cite_note-30">[30]</a></sup>`),
        new TextContent(`The most recent versions of the game's rules are detailed in three <a href="https://en.wikipedia.org//wiki/Dungeons_%26_Dragons_manuals" class="mw-redirect" title="Dungeons &amp; Dragons manuals">core rulebooks</a>: The <i><a href="https://en.wikipedia.org//wiki/Player%27s_Handbook" title="Player's Handbook">Player's Handbook</a></i>, the <i><a href="https://en.wikipedia.org//wiki/Dungeon_Master%27s_Guide" title="Dungeon Master's Guide">Dungeon Master's Guide</a></i> and the <i><a href="https://en.wikipedia.org//wiki/Monster_Manual" title="Monster Manual">Monster Manual</a></i>.<sup id="cite_ref-:6_18-1" class="reference"><a href="#cite_note-:6-18">[18]</a></sup>        `),
        new TextContent(`The only items required to play the game are the rulebooks, a <a href="https://en.wikipedia.org//wiki/Character_sheet" title="Character sheet">character sheet</a> for each player, and a number of <a href="https://en.wikipedia.org//wiki/Polyhedral_dice" class="mw-redirect" title="Polyhedral dice">polyhedral dice</a>. Many players also use miniature figures on a grid map as a visual aid if desired, particularly during combat. Some editions of the game presume such usage. Many optional accessories are available to enhance the game, such as expansion rulebooks, pre-designed adventures and various <a href="https://en.wikipedia.org//wiki/Dungeons_%26_Dragons_campaign_settings" title="Dungeons &amp; Dragons campaign settings">campaign settings</a>.<sup id="cite_ref-:6_18-2" class="reference"><a href="#cite_note-:6-18">[18]</a></sup><sup id="cite_ref-:7_22-2" class="reference"><a href="#cite_note-:7-22">[22]</a></sup>        `),
        chapter1p1,chapter1p2,chapter1p3
    ]
)
const chapter2p1:ChapterContent = new ClassiqueChapterContent(
    "Sources and influences",
    [
        new TextContent(`An immediate predecessor of <i>Dungeons &amp; Dragons</i> was a set of medieval miniature rules written by <a href="https://en.wikipedia.org//wiki/Jeff_Perren" title="Jeff Perren">Jeff Perren</a>. These were expanded by <a href="https://en.wikipedia.org//wiki/Gary_Gygax" title="Gary Gygax">Gary Gygax</a>, whose additions included a fantasy supplement, before the game was published as <i><a href="https://en.wikipedia.org//wiki/Chainmail_(game)" title="Chainmail (game)">Chainmail</a></i>. When <a href="https://en.wikipedia.org//wiki/Dave_Wesely" class="mw-redirect" title="Dave Wesely">Dave Wesely</a> entered the Army in 1970, his friend and fellow Napoleonics wargamer <a href="https://en.wikipedia.org//wiki/Dave_Arneson" title="Dave Arneson">Dave Arneson</a> began a medieval variation of Wesely's <a href="https://en.wikipedia.org//wiki/Braunstein_(wargame)" class="mw-redirect" title="Braunstein (wargame)">Braunstein</a> games, where players control individuals instead of armies.<sup id="cite_ref-DW3_64-0" class="reference"><a href="#cite_note-DW3-64">[64]</a></sup> Arneson used <i>Chainmail</i> to resolve combat.<sup id="cite_ref-Banshee_Gygax_6-1" class="reference"><a href="#cite_note-Banshee_Gygax-6">[6]</a></sup> As play progressed, Arneson added such innovations as character classes, experience points, level advancement, armor class, and others.<sup id="cite_ref-DW3_64-1" class="reference"><a href="#cite_note-DW3-64">[64]</a></sup> Having partnered previously with Gygax on <i><a href="https://en.wikipedia.org//wiki/Don%27t_Give_Up_the_Ship!" class="mw-redirect" title="Don't Give Up the Ship!">Don't Give Up the Ship!</a></i>, Arneson introduced Gygax to his Blackmoor game and the two then collaborated on developing "The Fantasy Game", the game that became <i>Dungeons &amp; Dragons</i>, with the final writing and preparation of the text being done by Gygax.<sup id="cite_ref-D&amp;Dfaq_65-0" class="reference"><a href="#cite_note-D&amp;Dfaq-65">[65]</a></sup><sup id="cite_ref-Wired_66-0" class="reference"><a href="#cite_note-Wired-66">[66]</a></sup><sup id="cite_ref-history_67-0" class="reference"><a href="#cite_note-history-67">[67]</a></sup> The name was chosen by Gygax's two-year-old daughter Cindy; upon being presented with a number of choices of possible names, she exclaimed, "Oh Daddy, I like Dungeons &amp; Dragons best!", although less prevalent versions of the story gave credit to his then wife Mary Jo.<sup id="cite_ref-witwer_68-0" class="reference"><a href="#cite_note-witwer-68">[68]</a></sup><sup class="reference nowrap"><span title="Page / location: 101">: 101 </span></sup>
`),
        new TextContent(`Many <i>Dungeons &amp; Dragons</i> elements appear in hobbies of the mid-to-late 20th century. For example, character-based role playing can be seen in <a href="https://en.wikipedia.org//wiki/Improvisational_theater" class="mw-redirect" title="Improvisational theater">improvisational theater</a>.<sup id="cite_ref-69" class="reference"><a href="#cite_note-69">[69]</a></sup> Game-world simulations were well developed in wargaming. Fantasy milieux specifically designed for gaming could be seen in <a href="https://en.wikipedia.org//wiki/Glorantha" title="Glorantha">Glorantha</a>'s board games among others.<sup id="cite_ref-Schick_17-34_70-0" class="reference"><a href="#cite_note-Schick_17-34-70">[70]</a></sup> Ultimately, however, <i>Dungeons &amp; Dragons</i> represents a unique blending of these elements.
        `),
        new TextContent(`The world of <i>D&amp;D</i> was influenced by world mythology, history, <a href="https://en.wikipedia.org//wiki/Pulp_magazine" title="Pulp magazine">pulp fiction</a>, and contemporary fantasy novels. The importance of <a href="https://en.wikipedia.org//wiki/J._R._R._Tolkien" title="J. R. R. Tolkien">J. R. R. Tolkien</a>'s <i><a href="https://en.wikipedia.org//wiki/The_Lord_of_the_Rings" title="The Lord of the Rings">The Lord of the Rings</a></i> and <i><a href="https://en.wikipedia.org//wiki/The_Hobbit" title="The Hobbit">The Hobbit</a></i> as an influence on <i>D&amp;D</i> is controversial. The presence in the game of <a href="https://en.wikipedia.org//wiki/Halfling_(Dungeons_%26_Dragons)" class="mw-redirect" title="Halfling (Dungeons &amp; Dragons)">halflings</a>, <a href="https://en.wikipedia.org//wiki/Elf_(Dungeons_%26_Dragons)" title="Elf (Dungeons &amp; Dragons)">elves</a>, <a href="https://en.wikipedia.org//wiki/Half-elf_(Dungeons_%26_Dragons)" title="Half-elf (Dungeons &amp; Dragons)">half-elves</a>, <a href="https://en.wikipedia.org//wiki/Dwarf_(Dungeons_%26_Dragons)" title="Dwarf (Dungeons &amp; Dragons)">dwarves</a>, orcs, <a href="https://en.wikipedia.org//wiki/Ranger_(Dungeons_%26_Dragons)" title="Ranger (Dungeons &amp; Dragons)">rangers</a>, and the like, draw comparisons to these works. The resemblance was even closer before the threat of copyright action from <a href="https://en.wikipedia.org//wiki/Middle-earth_Enterprises" title="Middle-earth Enterprises">Tolkien Enterprises</a> prompted the name changes of <a href="https://en.wikipedia.org//wiki/Hobbit" title="Hobbit">hobbit</a> to 'halfling', <a href="https://en.wikipedia.org//wiki/Ent" title="Ent">ent</a> to '<a href="https://en.wikipedia.org//wiki/Treant" class="mw-redirect" title="Treant">treant</a>', and <a href="https://en.wikipedia.org//wiki/Balrog" title="Balrog">balrog</a> to '<a href="https://en.wikipedia.org//wiki/Balor_(Dungeons_%26_Dragons)" class="mw-redirect" title="Balor (Dungeons &amp; Dragons)">balor</a>'. For many years, Gygax played down the influence of Tolkien on the development of the game.<sup id="cite_ref-71" class="reference"><a href="#cite_note-71">[71]</a></sup><sup id="cite_ref-Dragon95_72-0" class="reference"><a href="#cite_note-Dragon95-72">[72]</a></sup><sup id="cite_ref-73" class="reference"><a href="#cite_note-73">[73]</a></sup> However, in an interview in 2000, he acknowledged that Tolkien's work had a "strong impact" though he also said that the list of other influential authors was long.<sup id="cite_ref-74" class="reference"><a href="#cite_note-74">[74]</a></sup>
`),
        new TextContent(`The <i>D&amp;D</i> magic system, in which wizards memorize spells that are used up once cast and must be re-memorized the next day, was heavily influenced by the <i><a href="https://en.wikipedia.org//wiki/Dying_Earth_series" class="mw-redirect" title="Dying Earth series">Dying Earth</a></i> stories and novels of <a href="https://en.wikipedia.org//wiki/Jack_Vance" title="Jack Vance">Jack Vance</a>.<sup id="cite_ref-75" class="reference"><a href="#cite_note-75">[75]</a></sup> The original alignment system (which grouped all characters and creatures into 'Law', 'Neutrality' and 'Chaos') was derived from the novel <i><a href="https://en.wikipedia.org//wiki/Three_Hearts_and_Three_Lions" title="Three Hearts and Three Lions">Three Hearts and Three Lions</a></i> by <a href="https://en.wikipedia.org//wiki/Poul_Anderson" title="Poul Anderson">Poul Anderson</a>.<sup id="cite_ref-lit_source_76-0" class="reference"><a href="#cite_note-lit_source-76">[76]</a></sup> A troll described in this work influenced the <i>D&amp;D</i> definition of that monster.<sup id="cite_ref-Dragon95_72-1" class="reference"><a href="#cite_note-Dragon95-72">[72]</a></sup>
        `),
        new TextContent(`Other influences include the works of <a href="https://en.wikipedia.org//wiki/Robert_E._Howard" title="Robert E. Howard">Robert E. Howard</a>, <a href="https://en.wikipedia.org//wiki/Edgar_Rice_Burroughs" title="Edgar Rice Burroughs">Edgar Rice Burroughs</a>, <a href="https://en.wikipedia.org//wiki/A._Merritt" title="A. Merritt">A. Merritt</a>, <a href="https://en.wikipedia.org//wiki/H._P._Lovecraft" title="H. P. Lovecraft">H. P. Lovecraft</a>, <a href="https://en.wikipedia.org//wiki/Fritz_Leiber" title="Fritz Leiber">Fritz Leiber</a>, <a href="https://en.wikipedia.org//wiki/L._Sprague_de_Camp" title="L. Sprague de Camp">L. Sprague de Camp</a>, <a href="https://en.wikipedia.org//wiki/Fletcher_Pratt" title="Fletcher Pratt">Fletcher Pratt</a>, <a href="https://en.wikipedia.org//wiki/Roger_Zelazny" title="Roger Zelazny">Roger Zelazny</a>, and <a href="https://en.wikipedia.org//wiki/Michael_Moorcock" title="Michael Moorcock">Michael Moorcock</a>.<sup id="cite_ref-77" class="reference"><a href="#cite_note-77">[77]</a></sup> Monsters, spells, and magic items used in the game have been inspired by hundreds of individual works such as <a href="https://en.wikipedia.org//wiki/Van_vogt" class="mw-redirect" title="Van vogt">A. E. van Vogt's</a> "Black Destroyer", <a href="https://en.wikipedia.org//wiki/Coeurl" class="mw-redirect" title="Coeurl">Coeurl</a> (the <a href="https://en.wikipedia.org//wiki/Displacer_Beast" class="mw-redirect" title="Displacer Beast">Displacer Beast</a>), <a href="https://en.wikipedia.org//wiki/Lewis_Carroll" title="Lewis Carroll">Lewis Carroll</a>'s "<a href="https://en.wikipedia.org//wiki/Jabberwocky" title="Jabberwocky">Jabberwocky</a>" (<a href="https://en.wikipedia.org//wiki/Vorpal" class="mw-redirect" title="Vorpal">vorpal</a> sword) and the <a href="https://en.wikipedia.org//wiki/Book_of_Genesis" title="Book of Genesis">Book of Genesis</a> (the clerical spell 'Blade Barrier' was inspired by the "<a href="https://en.wikipedia.org//wiki/Flaming_sword_(mythology)" title="Flaming sword (mythology)">flaming sword</a> which turned every way" at the gates of <a href="https://en.wikipedia.org//wiki/Garden_of_Eden" title="Garden of Eden">Eden</a>).<sup id="cite_ref-lit_source_76-1" class="reference"><a href="#cite_note-lit_source-76">[76]</a></sup>
        `),

    ]
)
const chapter2:ChapterContent = new ClassiqueChapterContent(
    "Development history",
    [
        chapter2p1
    ]
)
const imageArray:ImageContent[] = [
    
    new ImageContent("/images/DD_Miniatures_2.jpg","Dungeons & Dragons miniature figures. The grid mat underneath uses one-inch squares."),
    new ImageContent("/images/DD_Miniatures_2.jpg","Dungeons & Dragons miniature figures. The grid mat underneath uses one-inch squares."),
    new ImageContent("/images/DD_Miniatures_2.jpg","Dungeons & Dragons miniature figures. The grid mat underneath uses one-inch squares."),
    new ImageContent("/images/DD_Miniatures_2.jpg","Dungeons & Dragons miniature figures. The grid mat underneath uses one-inch squares."),
    new ImageContent("/images/DD_Miniatures_2.jpg","Dungeons & Dragons miniature figures. The grid mat underneath uses one-inch squares."),
    new ImageContent("/images/DD_Miniatures_2.jpg","Dungeons & Dragons miniature figures. The grid mat underneath uses one-inch squares."),
    new ImageContent("/images/DD_Miniatures_2.jpg","Dungeons & Dragons miniature figures. The grid mat underneath uses one-inch squares."),
    new ImageContent("/images/DD_Miniatures_2.jpg","Dungeons & Dragons miniature figures. The grid mat underneath uses one-inch squares."),
    new ImageContent("/images/DD_Miniatures_2.jpg","Dungeons & Dragons miniature figures. The grid mat underneath uses one-inch squares."),
    new ImageContent("/images/DD_Miniatures_2.jpg","Dungeons & Dragons miniature figures. The grid mat underneath uses one-inch squares."),
    new ImageContent("/images/DD_Miniatures_2.jpg","Dungeons & Dragons miniature figures. The grid mat underneath uses one-inch squares."),
    new ImageContent("/images/DD_Miniatures_2.jpg","Dungeons & Dragons miniature figures. The grid mat underneath uses one-inch squares."),
    new ImageContent("/images/DD_Miniatures_2.jpg","Dungeons & Dragons miniature figures. The grid mat underneath uses one-inch squares."),
    new ImageContent("/images/DD_Miniatures_2.jpg","Dungeons & Dragons miniature figures. The grid mat underneath uses one-inch squares."),
    new ImageContent("/images/DD_Miniatures_2.jpg","Dungeons & Dragons miniature figures. The grid mat underneath uses one-inch squares."),
]
const chapter3:GalleryChapterContent = new GalleryChapterContent(
    "Gallery",
    imageArray
)


const summary= new SummaryContent(new TextContent(`<i><b>Dungeons &amp; Dragons</b></i> (commonly abbreviated as <i><b>D&amp;D</b></i> or <i><b>DnD</b></i>)<sup id="cite_ref-2" class="reference"><a href="#cite_note-2">[2]</a></sup> is a <a href="https://en.wikipedia.org//wiki/Fantasy" title="Fantasy">fantasy</a> <a href="https://en.wikipedia.org//wiki/Tabletop_role-playing_game" title="Tabletop role-playing game">tabletop role-playing game</a> (RPG) originally designed by <a href="https://en.wikipedia.org//wiki/Gary_Gygax" title="Gary Gygax">Gary Gygax</a> and <a href="https://en.wikipedia.org//wiki/Dave_Arneson" title="Dave Arneson">Dave Arneson</a>.<sup id="cite_ref-:5_3-0" class="reference"><a href="#cite_note-:5-3">[3]</a></sup><sup id="cite_ref-:1_4-0" class="reference"><a href="#cite_note-:1-4">[4]</a></sup><sup id="cite_ref-:2_5-0" class="reference"><a href="#cite_note-:2-5">[5]</a></sup> It was first published in 1974 by <a href="https://en.wikipedia.org//wiki/TSR_(company)#Tactical_Studies_Rules" class="mw-redirect" title="TSR (company)">Tactical Studies Rules, Inc.</a> (TSR).<sup id="cite_ref-:2_5-1" class="reference"><a href="#cite_note-:2-5">[5]</a></sup> It has been published by <a href="https://en.wikipedia.org//wiki/Wizards_of_the_Coast" title="Wizards of the Coast">Wizards of the Coast</a> (now a subsidiary of <a href="https://en.wikipedia.org//wiki/Hasbro" title="Hasbro">Hasbro</a>) since 1997. The game was derived from <a href="https://en.wikipedia.org//wiki/Miniature_wargaming" title="Miniature wargaming">miniature wargames</a>, with a variation of the 1971 game <a href="https://en.wikipedia.org//wiki/Chainmail_(game)" title="Chainmail (game)"><i>Chainmail</i></a> serving as the initial rule system.<sup id="cite_ref-:1_4-1" class="reference"><a href="#cite_note-:1-4">[4]</a></sup><sup id="cite_ref-Banshee_Gygax_6-0" class="reference"><a href="#cite_note-Banshee_Gygax-6">[6]</a></sup> <i>D&amp;D</i><span class="nowrap" style="padding-left:0.1em;">'s</span> publication is commonly recognized as the beginning of modern role-playing games and the role-playing game industry.<sup id="cite_ref-:2_5-2" class="reference"><a href="#cite_note-:2-5">[5]</a></sup><sup id="cite_ref-:3_7-0" class="reference"><a href="#cite_note-:3-7">[7]</a></sup>
</br>
<i>D&amp;D</i> departs from traditional <a href="https://en.wikipedia.org//wiki/Wargame" title="Wargame">wargaming</a> by allowing each player to create their own <a href="https://en.wikipedia.org//wiki/Player_character" title="Player character">character</a> to play instead of a <a href="https://en.wikipedia.org//wiki/Military_formation" class="mw-redirect" title="Military formation">military formation</a>. These characters embark upon imaginary adventures within a fantasy setting. A <a href="https://en.wikipedia.org//wiki/Dungeon_Master" title="Dungeon Master">Dungeon Master</a> (DM) serves as the game's referee and storyteller, while maintaining the setting in which the adventures occur, and playing the role of the inhabitants of the game world. The characters form a <a href="https://en.wikipedia.org//wiki/Party_(role-playing_games)" title="Party (role-playing games)">party</a> and they interact with the setting's inhabitants and each other. Together they solve dilemmas, engage in battles, explore, and gather treasure and knowledge. In the process, the characters earn <a href="https://en.wikipedia.org//wiki/Experience_point" title="Experience point">experience points</a> (XP) in order to rise in levels, and become increasingly powerful over a series of separate gaming sessions.<sup id="cite_ref-:5_3-1" class="reference"><a href="#cite_note-:5-3">[3]</a></sup><sup id="cite_ref-:3_7-1" class="reference"><a href="#cite_note-:3-7">[7]</a></sup><sup id="cite_ref-8" class="reference"><a href="#cite_note-8">[8]</a></sup>
</br>
The early success of <i>D&amp;D</i> led to a proliferation of similar game systems. Despite the competition, <i>D&amp;D</i> has remained the market leader in the role-playing game industry.<sup id="cite_ref-9" class="reference"><a href="#cite_note-9">[9]</a></sup><sup id="cite_ref-:4_10-0" class="reference"><a href="#cite_note-:4-10">[10]</a></sup> In 1977, the game was split into two branches: the relatively rules-light game system of <a href="https://en.wikipedia.org//wiki/Editions_of_Dungeons_%26_Dragons#Dungeons_&amp;_Dragons_Basic_Set_and_revisions" title="">basic <i>Dungeons &amp; Dragons</i></a>, and the more structured, rules-heavy game system of <i><a href="https://en.wikipedia.org//wiki/Editions_of_Dungeons_%26_Dragons#Advanced_Dungeons_&amp;_Dragons" title="Editions of Dungeons &amp; Dragons">Advanced Dungeons &amp; Dragons</a></i> (abbreviated as <i>AD&amp;D</i>).<sup id="cite_ref-Dragon_26_Gygax_11-0" class="reference"><a href="#cite_note-Dragon_26_Gygax-11">[11]</a></sup><sup id="cite_ref-12" class="reference"><a href="#cite_note-12">[12]</a></sup><sup id="cite_ref-13" class="reference"><a href="#cite_note-13">[13]</a></sup> <i>AD&amp;D</i> 2nd Edition was published in 1989. In 2000, a new system was released as <i>D&amp;D</i> 3rd edition, continuing the edition numbering from <i>AD&amp;D</i>; a revised version 3.5 was released in June 2003. These 3rd edition rules formed the basis of the <a href="https://en.wikipedia.org//wiki/D20_system" class="mw-redirect" title="D20 system">d20 System</a>, which is available under the <a href="https://en.wikipedia.org//wiki/Open_Game_License" title="Open Game License">Open Game License</a> (OGL) for use by other publishers. <i>D&amp;D</i> 4th edition was released in June 2008.<sup id="cite_ref-14" class="reference"><a href="#cite_note-14">[14]</a></sup> The 5th edition of <i>D&amp;D</i>, the most recent, was released during the second half of 2014.<sup id="cite_ref-:4_10-1" class="reference"><a href="#cite_note-:4-10">[10]</a></sup>
</br>
In 2004, <i>D&amp;D</i> remained the best-known,<sup id="cite_ref-15" class="reference"><a href="#cite_note-15">[15]</a></sup> and best-selling,<sup id="cite_ref-16" class="reference"><a href="#cite_note-16">[16]</a></sup> role-playing game in the US, with an estimated 20 million people having played the game, and more than US$1 billion in book and equipment sales worldwide.<sup id="cite_ref-:5_3-2" class="reference"><a href="#cite_note-:5-3">[3]</a></sup> The year 2017 had "the most number of players in its history—12 million to 15 million in North America alone".<sup id="cite_ref-Brodeur_17-0" class="reference"><a href="#cite_note-Brodeur-17">[17]</a></sup> <i>D&amp;D 5th edition</i> sales "were up 41 percent in 2017 from the year before, and soared another 52 percent in 2018, the game's biggest sales year yet".<sup id="cite_ref-:4_10-2" class="reference"><a href="#cite_note-:4-10">[10]</a></sup> The game has been supplemented by many pre-made <a href="https://en.wikipedia.org//wiki/Adventure_(Dungeons_%26_Dragons)" title="Adventure (Dungeons &amp; Dragons)">adventures</a>, as well as commercial <a href="https://en.wikipedia.org//wiki/Dungeons_%26_Dragons_campaign_settings" title="Dungeons &amp; Dragons campaign settings">campaign settings</a> suitable for use by regular gaming groups.<sup id="cite_ref-:6_18-0" class="reference"><a href="#cite_note-:6-18">[18]</a></sup> <i>D&amp;D</i> is known beyond the game itself for other <a href="https://en.wikipedia.org//wiki/Dungeons_%26_Dragons-related_products" class="mw-redirect" title="Dungeons &amp; Dragons-related products"><i>D&amp;D</i>-branded products</a>, <a href="https://en.wikipedia.org//wiki/Dungeons_%26_Dragons_in_popular_culture" title="Dungeons &amp; Dragons in popular culture">references in popular culture</a>, and some of the <a href="https://en.wikipedia.org//wiki/Dungeons_%26_Dragons_controversies" title="Dungeons &amp; Dragons controversies">controversies</a> that have surrounded it, particularly a <a href="https://en.wikipedia.org//wiki/Moral_panic" title="Moral panic">moral panic</a> in the 1980s falsely linking it to <a href="https://en.wikipedia.org//wiki/Satanism" title="Satanism">Satanism</a> and <a href="https://en.wikipedia.org//wiki/Suicide" title="Suicide">suicide</a>.<sup id="cite_ref-:5_3-3" class="reference"><a href="#cite_note-:5-3">[3]</a></sup><sup id="cite_ref-Moral_Panic_19-0" class="reference"><a href="#cite_note-Moral_Panic-19">[19]</a></sup><sup id="cite_ref-20" class="reference"><a href="#cite_note-20">[20]</a></sup> The game has won multiple awards and has been translated into many languages.
`))

const infoBox = new InfoBoxContent([new TextContent(`Designers	Gary Gygax
Dave Arneson
Publishers	TSR (1974–1997), Wizards of the Coast (1997–present)`)])

const reference = new ReferencesContent([
    new TextContent(`<span class="mw-cite-backlink"><b><a href="#cite_ref-acdd_1-0" aria-label="Jump up" title="Jump up">^</a></b></span> <span class="reference-text"><style data-mw-deduplicate="TemplateStyles:r1067248974">.mw-parser-output cite.citation{font-style:inherit;word-wrap:break-word}.mw-parser-output .citation q{quotes:"\"""\"""'""'"}.mw-parser-output .citation:target{background-color:rgba(0,127,255,0.133)}.mw-parser-output .id-lock-free a,.mw-parser-output .citation .cs1-lock-free a{background:linear-gradient(transparent,transparent),url("//upload.wikimedia.org/wikipedia/commons/6/65/Lock-green.svg")right 0.1em center/9px no-repeat}.mw-parser-output .id-lock-limited a,.mw-parser-output .id-lock-registration a,.mw-parser-output .citation .cs1-lock-limited a,.mw-parser-output .citation .cs1-lock-registration a{background:linear-gradient(transparent,transparent),url("//upload.wikimedia.org/wikipedia/commons/d/d6/Lock-gray-alt-2.svg")right 0.1em center/9px no-repeat}.mw-parser-output .id-lock-subscription a,.mw-parser-output .citation .cs1-lock-subscription a{background:linear-gradient(transparent,transparent),url("//upload.wikimedia.org/wikipedia/commons/a/aa/Lock-red-alt-2.svg")right 0.1em center/9px no-repeat}.mw-parser-output .cs1-ws-icon a{background:linear-gradient(transparent,transparent),url("//upload.wikimedia.org/wikipedia/commons/4/4c/Wikisource-logo.svg")right 0.1em center/12px no-repeat}.mw-parser-output .cs1-code{color:inherit;background:inherit;border:none;padding:inherit}.mw-parser-output .cs1-hidden-error{display:none;color:#d33}.mw-parser-output .cs1-visible-error{color:#d33}.mw-parser-output .cs1-maint{display:none;color:#3a3;margin-left:0.3em}.mw-parser-output .cs1-format{font-size:95%}.mw-parser-output .cs1-kern-left{padding-left:0.2em}.mw-parser-output .cs1-kern-right{padding-right:0.2em}.mw-parser-output .citation .mw-selflink{font-weight:inherit}</style><cite class="citation web cs1"><a rel="nofollow" class="external text" href="http://www.acaeum.com/ddindexes/setpages/basic.html">"D&amp;D Basic Set"</a>. <i>Rulebooks and Sets</i>. acaeum.com. <a rel="nofollow" class="external text" href="https://web.archive.org/web/20110624215519/http://acaeum.com/ddindexes/setpages/basic.html">Archived</a> from the original on June 24, 2011<span class="reference-accessdate">. Retrieved <span class="nowrap">May 16,</span> 2013</span>.</cite><span title="ctx_ver=Z39.88-2004&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Ajournal&amp;rft.genre=unknown&amp;rft.jtitle=Rulebooks+and+Sets&amp;rft.atitle=D%26D+Basic+Set&amp;rft_id=http%3A%2F%2Fwww.acaeum.com%2Fddindexes%2Fsetpages%2Fbasic.html&amp;rfr_id=info%3Asid%2Fen.wikipedia.org%3ADungeons+%26+Dragons" class="Z3988"></span></span>
`),
    new TextContent(`<span class="mw-cite-backlink"><b><a href="#cite_ref-2" aria-label="Jump up" title="Jump up">^</a></b></span> <span class="reference-text"><link rel="mw-deduplicated-inline-style" href="mw-data:TemplateStyles:r1067248974"><cite class="citation web cs1"><a rel="nofollow" class="external text" href="https://www.geeknative.com/64619/dd-the-what-does-that-stand-for-list/">"D&amp;D: The 'What does that stand for?' list"</a>. <i>Geek Native</i>. February 18, 2019<span class="reference-accessdate">. Retrieved <span class="nowrap">February 25,</span> 2020</span>.</cite><span title="ctx_ver=Z39.88-2004&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Ajournal&amp;rft.genre=unknown&amp;rft.jtitle=Geek+Native&amp;rft.atitle=D%26D%3A+The+%27What+does+that+stand+for%3F%27+list&amp;rft.date=2019-02-18&amp;rft_id=https%3A%2F%2Fwww.geeknative.com%2F64619%2Fdd-the-what-does-that-stand-for-list%2F&amp;rfr_id=info%3Asid%2Fen.wikipedia.org%3ADungeons+%26+Dragons" class="Z3988"></span></span>
    `),
    new TextContent(`<span class="mw-cite-backlink">^ <a href="#cite_ref-:5_3-0"><span class="cite-accessibility-label">Jump up to: </span><sup><i><b>a</b></i></sup></a> <a href="#cite_ref-:5_3-1"><sup><i><b>b</b></i></sup></a> <a href="#cite_ref-:5_3-2"><sup><i><b>c</b></i></sup></a> <a href="#cite_ref-:5_3-3"><sup><i><b>d</b></i></sup></a></span> <span class="reference-text"><link rel="mw-deduplicated-inline-style" href="mw-data:TemplateStyles:r1067248974"><cite id="CITEREFWaters2004" class="citation news cs1">Waters, Darren (April 26, 2004). <a rel="nofollow" class="external text" href="http://news.bbc.co.uk/2/hi/uk_news/magazine/3655627.stm">"What happened to Dungeons and Dragons?"</a>. <i><a href="/wiki/BBC_News" title="BBC News">BBC News</a></i><span class="reference-accessdate">. Retrieved <span class="nowrap">February 25,</span> 2020</span>.</cite><span title="ctx_ver=Z39.88-2004&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Ajournal&amp;rft.genre=article&amp;rft.jtitle=BBC+News&amp;rft.atitle=What+happened+to+Dungeons+and+Dragons%3F&amp;rft.date=2004-04-26&amp;rft.aulast=Waters&amp;rft.aufirst=Darren&amp;rft_id=http%3A%2F%2Fnews.bbc.co.uk%2F2%2Fhi%2Fuk_news%2Fmagazine%2F3655627.stm&amp;rfr_id=info%3Asid%2Fen.wikipedia.org%3ADungeons+%26+Dragons" class="Z3988"></span></span>
    `),
    new TextContent(`<span class="mw-cite-backlink">^ <a href="#cite_ref-:1_4-0"><span class="cite-accessibility-label">Jump up to: </span><sup><i><b>a</b></i></sup></a> <a href="#cite_ref-:1_4-1"><sup><i><b>b</b></i></sup></a></span> <span class="reference-text"><link rel="mw-deduplicated-inline-style" href="mw-data:TemplateStyles:r1067248974"><cite id="CITEREFD'Anastasio2019" class="citation web cs1">D'Anastasio, Cecilia (August 26, 2019). <a rel="nofollow" class="external text" href="https://kotaku.com/dungeons-deceptions-the-first-d-d-players-push-back-1837516834">"Dungeons &amp; Deceptions: The First D&amp;D Players Push Back On The Legend Of Gary Gygax"</a>. <i><a href="/wiki/Kotaku" title="Kotaku">Kotaku</a></i><span class="reference-accessdate">. Retrieved <span class="nowrap">February 25,</span> 2020</span>.</cite><span title="ctx_ver=Z39.88-2004&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Ajournal&amp;rft.genre=unknown&amp;rft.jtitle=Kotaku&amp;rft.atitle=Dungeons+%26+Deceptions%3A+The+First+D%26D+Players+Push+Back+On+The+Legend+Of+Gary+Gygax&amp;rft.date=2019-08-26&amp;rft.aulast=D%27Anastasio&amp;rft.aufirst=Cecilia&amp;rft_id=https%3A%2F%2Fkotaku.com%2Fdungeons-deceptions-the-first-d-d-players-push-back-1837516834&amp;rfr_id=info%3Asid%2Fen.wikipedia.org%3ADungeons+%26+Dragons" class="Z3988"></span></span>
    `),
    new TextContent(`<span class="mw-cite-backlink">^ <a href="#cite_ref-:2_5-0"><span class="cite-accessibility-label">Jump up to: </span><sup><i><b>a</b></i></sup></a> <a href="#cite_ref-:2_5-1"><sup><i><b>b</b></i></sup></a> <a href="#cite_ref-:2_5-2"><sup><i><b>c</b></i></sup></a></span> <span class="reference-text"><link rel="mw-deduplicated-inline-style" href="mw-data:TemplateStyles:r1067248974"><cite id="CITEREFMichaud2015" class="citation magazine cs1">Michaud, Jon (November 2, 2015). <a rel="nofollow" class="external text" href="https://www.newyorker.com/books/page-turner/the-tangled-cultural-roots-of-dungeons-dragons">"The Tangled Cultural Roots of Dungeons &amp; Dragons"</a>. <i><a href="/wiki/The_New_Yorker" title="The New Yorker">The New Yorker</a></i><span class="reference-accessdate">. Retrieved <span class="nowrap">February 25,</span> 2020</span>.</cite><span title="ctx_ver=Z39.88-2004&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Ajournal&amp;rft.genre=article&amp;rft.jtitle=The+New+Yorker&amp;rft.atitle=The+Tangled+Cultural+Roots+of+Dungeons+%26+Dragons&amp;rft.date=2015-11-02&amp;rft.aulast=Michaud&amp;rft.aufirst=Jon&amp;rft_id=https%3A%2F%2Fwww.newyorker.com%2Fbooks%2Fpage-turner%2Fthe-tangled-cultural-roots-of-dungeons-dragons&amp;rfr_id=info%3Asid%2Fen.wikipedia.org%3ADungeons+%26+Dragons" class="Z3988"></span></span>
    `),
    new TextContent(`<span class="mw-cite-backlink">^ <a href="#cite_ref-Banshee_Gygax_6-0"><span class="cite-accessibility-label">Jump up to: </span><sup><i><b>a</b></i></sup></a> <a href="#cite_ref-Banshee_Gygax_6-1"><sup><i><b>b</b></i></sup></a></span> <span class="reference-text"><a href="#CITEREFBirnbaum2004">Birnbaum 2004</a></span>
    `),
    new TextContent(`<span class="mw-cite-backlink">^ <a href="#cite_ref-:3_7-0"><span class="cite-accessibility-label">Jump up to: </span><sup><i><b>a</b></i></sup></a> <a href="#cite_ref-:3_7-1"><sup><i><b>b</b></i></sup></a> <a href="#cite_ref-:3_7-2"><sup><i><b>c</b></i></sup></a> <a href="#cite_ref-:3_7-3"><sup><i><b>d</b></i></sup></a> <a href="#cite_ref-:3_7-4"><sup><i><b>e</b></i></sup></a></span> <span class="reference-text"><link rel="mw-deduplicated-inline-style" href="mw-data:TemplateStyles:r1067248974"><cite id="CITEREFJ._Patrick_WilliamsSean_Q._HendricksW._Keith_Winkler2006" class="citation book cs1">J. Patrick Williams; Sean Q. Hendricks; W. Keith Winkler (2006). <i>Gaming as Culture, Essays on Reality, Identity and Experience in Fantasy Games</i>. Jefferson, N.C.: McFarland &amp; Company. pp.&nbsp;1–14, 27. <a href="/wiki/ISBN_(identifier)" class="mw-redirect" title="ISBN (identifier)">ISBN</a>&nbsp;<a href="/wiki/Special:BookSources/0-7864-2436-2" title="Special:BookSources/0-7864-2436-2"><bdi>0-7864-2436-2</bdi></a>. <a href="/wiki/OCLC_(identifier)" class="mw-redirect" title="OCLC (identifier)">OCLC</a>&nbsp;<a rel="nofollow" class="external text" href="//www.worldcat.org/oclc/63122794">63122794</a>.</cite><span title="ctx_ver=Z39.88-2004&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Abook&amp;rft.genre=book&amp;rft.btitle=Gaming+as+Culture%2C+Essays+on+Reality%2C+Identity+and+Experience+in+Fantasy+Games&amp;rft.place=Jefferson%2C+N.C.&amp;rft.pages=1-14%2C+27&amp;rft.pub=McFarland+%26+Company&amp;rft.date=2006&amp;rft_id=info%3Aoclcnum%2F63122794&amp;rft.isbn=0-7864-2436-2&amp;rft.au=J.+Patrick+Williams&amp;rft.au=Sean+Q.+Hendricks&amp;rft.au=W.+Keith+Winkler&amp;rfr_id=info%3Asid%2Fen.wikipedia.org%3ADungeons+%26+Dragons" class="Z3988"></span></span>
`),
])

const relatedSubject = new RelatedSubjectContent([
    new TextContent(`<ul><li><span class="official-website"><span class="url"><a rel="nofollow" class="external text" href="https://dnd.wizards.com">Official website</a></span></span> <a href="https://www.wikidata.org/wiki/Q1375#P856" title="Edit this at Wikidata"><img alt="Edit this at Wikidata" src="//upload.wikimedia.org/wikipedia/en/thumb/8/8a/OOjs_UI_icon_edit-ltr-progressive.svg/10px-OOjs_UI_icon_edit-ltr-progressive.svg.png" decoding="async" width="10" height="10" style="vertical-align: text-top" srcset="//upload.wikimedia.org/wikipedia/en/thumb/8/8a/OOjs_UI_icon_edit-ltr-progressive.svg/15px-OOjs_UI_icon_edit-ltr-progressive.svg.png 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/8/8a/OOjs_UI_icon_edit-ltr-progressive.svg/20px-OOjs_UI_icon_edit-ltr-progressive.svg.png 2x" data-file-width="20" data-file-height="20"></a></li>
    <li><a rel="nofollow" class="external text" href="https://curlie.org/Games/Roleplaying/Genres/Fantasy/Dungeons_&amp;_Dragons">Dungeons &amp; Dragons</a> at <a href="/wiki/Curlie" class="mw-redirect" title="Curlie">Curlie</a></li>
    <li><link rel="mw-deduplicated-inline-style" href="mw-data:TemplateStyles:r1067248974"><cite id="CITEREFOff_Book2013" class="citation web cs1"><a href="/wiki/Off_Book_(web_series)" class="mw-redirect" title="Off Book (web series)">Off Book</a> (June 20, 2013). <a rel="nofollow" class="external text" href="http://video.pbs.org/video/2365039841/">"<i>Dungeons &amp; Dragons</i> and the Influence of Tabletop RPGs"</a>. PBS.</cite><span title="ctx_ver=Z39.88-2004&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Abook&amp;rft.genre=unknown&amp;rft.btitle=Dungeons+%26+Dragons+and+the+Influence+of+Tabletop+RPGs&amp;rft.pub=PBS&amp;rft.date=2013-06-20&amp;rft.au=Off+Book&amp;rft_id=http%3A%2F%2Fvideo.pbs.org%2Fvideo%2F2365039841%2F&amp;rfr_id=info%3Asid%2Fen.wikipedia.org%3ADungeons+%26+Dragons" class="Z3988"></span></li></ul>
    `)
])

export const dungeonsAndDragons:SubjectContent = new SubjectContent(
    {
        url:"dungeons-drangons",
        subject:"Dungeons & Dragons",
        chapters:[chapter1,chapter2,chapter3],
        summary: summary,
        tableOfContent:new TOCContent([{content:"Play overview",url:""},{content:"Development history",url:""}]),
        infoBox:infoBox,
        reference:reference,
        relatedSubject:relatedSubject
    }
)